In [ ]:
import pandas as pd

In [ ]:
# pd.Series()
# 시리즈 만들기

menu = pd.Series(['비빔밥', '김치찌개', '된장찌개'])
price = pd.Series([10000, 9000, 8000])

In [ ]:
# pd.DataFrame()
# 데이터 프레임 만들기

pd.DataFrame({
    "메뉴" : menu,
    "가격" : price
})

df = pd.DataFrame({
    "메뉴" : ["비빔밥", "김치찌개", "된장찌개"],
    "가격" : [10000, 9000, 8000],
    "원산지" : ["국내산", "국내산", "국내산"]
})

In [ ]:
# csv 파일로 저장하기
df.to_csv('temp.csv')

# csv 파일로 저장하기(인덱스 제외)
df.to_csv('temp.csv', index=False)


# csv 파일 불러오기
temp_df = pd.read_csv('temp.csv')

# csv 파일 불러오기(인덱스로 사용할 컬럼명 또는 열의 번호 지정)
pd.read_csv('temp.csv', index_col='컬럼명')
pd.read_csv('temp.csv', index_col=0)

# csv 파일 불러오기(불러올 컬럼명 또는 열의 번호 지정)
pd.read_csv('temp.csv', usecols=['메뉴', '가격'])
pd.read_csv('temp.csv', usecols=[0, 1])

In [ ]:
# 상위 N개의 행 반환
df.head(3)

# 하위 N개의 행 반환
df.tail(4)

# 샘플링(데이터프레임에서 임의로 샘플링해 N개의 행 반환)
df.sample(3)

# 데이터프레임의 크기(행, 열)
df.shape

# 숫자형 컬럼 간 상관관계 확인
df.corr(numeric_only=True)

In [ ]:
# 데이터프레임 안 컬럼의 자료형 확인
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   메뉴      7 non-null      object
 1   가격      7 non-null      int64
 2   칼로리     7 non-null      int64
dtypes: int64(2), object(1)
memory usage: 300.0+ bytes

In [ ]:
# unique(): 시리즈에서 고유한 값
df_car['car'].unique()

# nunique(): 시리즈에서 고유한 값 개수
df_car['car'].nunique()

# nunique(): 데이터프레임에서 고유한 값 개수
df_car.nunique()


# value_counts(): unique()와 nuique()의 결과 내용을 한 번에 확인
print(df_car['car'].value_counts())
print()
print(df_car['size'].value_counts())

In [ ]:
# value_counts(): unique()와 nuique()의 결과 내용을 한 번에 확인
print(df_car['car'].value_counts())
print()
print(df_car['size'].value_counts())

car
Sedan    7
SUV      4
Name: count, dtype: int64

size
S    6
M    4
L    1
Name: count, dtype: int64

In [ ]:
# describe(): 수치형 데이터에 대한 기술통계량
# count: 값이 있는 데이터 수, mean: 평균, std: 표준편차, min: 최솟값, 00%: 백분위수에서 00%, max: 최댓값
df.describe()

                가격         칼로리
count     7.000000    7.000000
mean   5028.571429  101.428571
std     631.702160   99.402980
min    4000.000000    0.000000
25%    4750.000000   15.000000
50%    5000.000000  110.000000
75%    5400.000000  160.000000
max    5900.000000  250.000000

In [ ]:
# describe(include="O"): 범주형(object 자료형) 데이터에 대한 기술통계량
# count: 값이 있는 데이터 수, unique: 고유한 데이터의 수(종류), top: 가장 많이 나오는 값(최빈값), freq: 가장 많이 나오는 값의 빈도 수
df_car.describe(include="O")

          car size
count      11   11
unique      2    3
top     Sedan    S
freq        7    6

In [ ]:
# astype(): 자료형 변경

# float -> int
df['가격'] = df['가격'].astype('int')
df.info()

# object -> float
df['칼로리'] = df['칼로리'].astype('float')
df.info()

In [ ]:
# 새로운 컬럼 추가(0으로 초기화)
df['new'] = 0

# 새로운 컬럼 추가(기존 컬럼 활용)
df['할인가'] = df['가격'] * 0.8

# drop(): 행 혹은 열 삭제 / axis=0: 행, axis=1: 열
# inplace 파라미터를 사용해야 삭제된 결과값이 저장됨. 혹은 inplace 대신 '='으로 저장
# 실수 방지를 위해 삭제 전후의 데이터 크기를 df.shape로 확인

# 행 삭제
df.drop(1, axis=0, inplace=True) # df = df.drop(1, axis=0)
df.head(3)

# 열 삭제
df = df.drop('칼로리', axis=1) # df.drop('칼로리', axis=1, inplace=True)
df.head(3)

In [ ]:
# loc: location의 약자로, 인덱스명 또는 컬럼명을 통해 데이터에 접근
df.loc[0]

# 0번째 행의 가격
df.loc[0, "가격"]

# location을 활용한 슬라이싱
# 전체 데이터 중, 가격
df.loc[:, "가격"]

# 0번째 행의 열들 중에서 메뉴부터 칼로리 사이의 열 출력
df.loc[0, '메뉴':'칼로리']

# 0번째 행의 열들 중에서 특정 열 출력
df.loc[0, ['메뉴', '칼로리']]

# 0~2번째 행의 열들 중에서 메뉴부터 가격까지 출력
df.loc[0:2, '메뉴':'가격']

In [ ]:
# iloc: integer location의 약자로, 행이나 열의 순서에 따른 인덱스 번호로 값을 슬라이싱하여 데이터에 접근
df.iloc[0]

#df.loc[1, '메뉴']
df.iloc[0, 0]

df.iloc[:, 1]

df.iloc[2, 0:2]

df.iloc[1:3, :]

In [ ]:
# 넘파이를 활용하여 결측지(NaN)가 있는 데이터 생성
import numpy as np
df['원산지'] = np.nan

# 인덱스명이 0인 행의 원산지 컬럼의 값을 콜롬비아로 변경
df.loc[0, "원산지"] = '콜롬비아'
# 인덱스명이 2~3인 행의 원산지 컬럼의 값을 과테말라로 변경
df.loc[2:3, "원산지"] = '과테말라'

# 인덱스명 7로 딕셔너리 형태로 행 추가. 원산지 컬럼은 지정하지 않았기 때문에 결측치인 NaN으로 채워짐.
df.loc[7] = {"메뉴" : "딴짓커피", "가격" : 2000, "칼로리" : 20}

In [ ]:
# sort_index(): 인덱스 기준 정렬
df.sort_index(ascending=False)

# sort_values(): 데이터 값 기준 정렬
df.sort_values('메뉴', ascending=False)

# 가격 내림차순, 메뉴 오름차순(= 가격 DESC, 메뉴 ASC)
df = df.sort_values(['가격', '메뉴'], ascending=[False, True])

# df의 인덱스명 순서가 변경되었으므로, 다시 0부터 7까지 새롭게 지정
df = df.reset_index(drop=True)

In [ ]:
# ~: NOT연산자
df[~cond]

# & 연산자: AND 연산이며, 가격이 5000원 이상이면서 칼로리가 100보다 큰 데이터 필터링
cond1 = (df['가격'] >= 5000)
cond2 = (df['칼로리'] > 100)
df[cond1 & cond2]

# | 연산자: OR 연산이며, 가격이 5000원 이상이거나 칼로리가 100보다 큰 데이터 필터링
cond1 = (df['가격'] >= 5000)
cond2 = (df['칼로리'] > 100)
df[cond1 | cond2]

# isin(): 주어진 값이 있는지 확인
cond = df['메뉴'].isin(['녹차'])
df[cond]

box = ['녹차', '카푸치노', '카페라떼']
cond = df['메뉴'].isin(box)
df[cond]

In [ ]:
# 12.결측치 처리


# 결측치 확인(결측치면 True)
df.isnull()

# 결측치이면 1이기 때문에 결측치의 갯수만큼 나옴
df.isnull().sum() # df.isna().sum()
df.isna().sum() # df.isnull().sum()

# fillna(): 결측치를 임의의 값으로 채움.
# '원산지' 컬럼에 있는 결측치를 '코스타리카'로 채움.
df['원산지'] = df['원산지'].fillna('코스타리카')
df