In [2]:
import pandas as pd

In [3]:
# pd.Series()
# 시리즈 만들기

menu = pd.Series(['비빔밥', '김치찌개', '된장찌개'])
price = pd.Series([10000, 9000, 8000])

In [ ]:
# pd.DataFrame()
# 데이터 프레임 만들기

pd.DataFrame({
    "메뉴" : menu,
    "가격" : price
})

df = pd.DataFrame({
    "메뉴" : ["비빔밥", "김치찌개", "된장찌개"],
    "가격" : [10000, 9000, 8000],
    "원산지" : ["국내산", "국내산", "국내산"]
})

In [ ]:
# csv 파일로 저장하기
df.to_csv('temp.csv')

# csv 파일로 저장하기(인덱스 제외)
df.to_csv('temp.csv', index=False)


# csv 파일 불러오기
temp_df = pd.read_csv('temp.csv')

# csv 파일 불러오기(인덱스로 사용할 컬럼명 또는 열의 번호 지정)
pd.read_csv('temp.csv', index_col='컬럼명')
pd.read_csv('temp.csv', index_col=0)

# csv 파일 불러오기(불러올 컬럼명 또는 열의 번호 지정)
pd.read_csv('temp.csv', usecols=['메뉴', '가격'])
pd.read_csv('temp.csv', usecols=[0, 1])

In [ ]:
# 상위 N개의 행 반환
df.head(3)

# 하위 N개의 행 반환
df.tail(4)

# 샘플링(데이터프레임에서 임의로 샘플링해 N개의 행 반환)
df.sample(3)

# 데이터프레임의 크기(행, 열)
df.shape

# 숫자형 컬럼 간 상관관계 확인
df.corr(numeric_only=True)

In [ ]:
# 데이터프레임 안 컬럼의 자료형 확인
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   메뉴      7 non-null      object
 1   가격      7 non-null      int64
 2   칼로리     7 non-null      int64
dtypes: int64(2), object(1)
memory usage: 300.0+ bytes

In [ ]:
# unique(): 시리즈에서 고유한 값
df_car['car'].unique()

# nunique(): 시리즈에서 고유한 값 개수
df_car['car'].nunique()

# nunique(): 데이터프레임에서 고유한 값 개수
df_car.nunique()


# value_counts(): unique()와 nuique()의 결과 내용을 한 번에 확인
print(df_car['car'].value_counts())
print()
print(df_car['size'].value_counts())

In [ ]:
# value_counts(): unique()와 nuique()의 결과 내용을 한 번에 확인
print(df_car['car'].value_counts())
print()
print(df_car['size'].value_counts())

car
Sedan    7
SUV      4
Name: count, dtype: int64

size
S    6
M    4
L    1
Name: count, dtype: int64

In [ ]:
# describe(): 수치형 데이터에 대한 기술통계량
# count: 값이 있는 데이터 수, mean: 평균, std: 표준편차, min: 최솟값, 00%: 백분위수에서 00%, max: 최댓값
df.describe()

                가격         칼로리
count     7.000000    7.000000
mean   5028.571429  101.428571
std     631.702160   99.402980
min    4000.000000    0.000000
25%    4750.000000   15.000000
50%    5000.000000  110.000000
75%    5400.000000  160.000000
max    5900.000000  250.000000

In [ ]:
# describe(include="O"): 범주형(object 자료형) 데이터에 대한 기술통계량
# count: 값이 있는 데이터 수, unique: 고유한 데이터의 수(종류), top: 가장 많이 나오는 값(최빈값), freq: 가장 많이 나오는 값의 빈도 수
df_car.describe(include="O")

          car size
count      11   11
unique      2    3
top     Sedan    S
freq        7    6

In [ ]:
# astype(): 자료형 변경

# float -> int
df['가격'] = df['가격'].astype('int')
df.info()

# object -> float
df['칼로리'] = df['칼로리'].astype('float')
df.info()